; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
framework = arduino
monitor_speed = 115200
lib_deps = 
	arduino-libraries/SD@^1.2.4
	adafruit/Adafruit ADS1X15@^2.6.0
build_flags = 
	-u_printf_float
	-u_scanf_float
	-Wl,-u,_printf_float
   -Wl,-u,_scanf_float
   -DHAL_FDCAN_MODULE_ENABLED

[env:nucleo_g474re]
board = nucleo_g474re
; RAM   = 131k
; Flash = 524k

[env:nucleo_h753zi]
board = nucleo_h753zi
; RAM   = 524k
; Flash = 2M
